# Generated by Django 3.2 on 2021-05-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('slug', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='該当箇所'),
        ),
        migrations.AlterField(
            model_name='card',
            name='subtitle',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='サブタイトル'),
        ),
        migrations.AlterField(
            model_name='card',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(blank=True, to='learning.Tag'),
        ),
    ]
